# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 433fccde72b029abf7df5149fab1af4702ff795935f6abdd73f695aaccc22f950aeacb97e6af180ebe1b6befb2df4aa2f22d9ef630a8979a0baea3b4c328c98f

test:
  secret_key_base: 385e70e266e30c9b988754832436fef7b5e81478029dbb6857a341583edecf1528c5c17227b0dd8407aa9422e8e0b205cdff4d1f6bdc8abe127a7121308a08b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
