# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d0d3d9283c75622cba2da3da572c96cbd8d73c2799a28269baece413e650e254c314638b9c76af57f98474157d8daa3630fac4e315d0614c1deb005ee43e341

test:
  secret_key_base: e6d6cdfdd95cb6f23f7302152a8f69927232b09f453cb98e79496b6e9b9623c505eb6debb7a37a34f3518e06985f7ba15cc834dfdc828bd3dfca123dbfa7c2a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
